"use client";
import { useState, type ReactNode } from "react";
import { ArrowUpRight, Check, CircleHelp, ExternalLink, FileCheck2, FileText, Loader2, ShieldCheck, Sparkles, AlertTriangle, XCircle, RefreshCw } from "lucide-react";

const packet=[
 {name:"W-9.pdf",type:"IRS tax form",status:"READY",detail:"Public form template · demo fields"},
 {name:"Certificate_of_Liability_Insurance.pdf",type:"ACORD 25 sample",status:"READY",detail:"Public procurement sample · sanitized"},
 {name:"Carrier_Agreement.pdf",type:"Broker agreement",status:"MISSING",detail:"Required before activation"}
];
const checks=[
 {label:"Carrier identity",value:"Matched",tone:"pass",detail:"Legal name and carrier identifiers are consistent across the review record."},
 {label:"Operating authority",value:"Verified",tone:"pass",detail:"Public FMCSA SAFER record is available for the carrier lookup."},
 {label:"Auto liability",value:"$1,000,000",tone:"pass",detail:"Meets the demo broker requirement of $1M."},
 {label:"Cargo coverage",value:"$50,000",tone:"block",detail:"Below the demo broker requirement of $100,000."},
 {label:"COI expiry",value:"18 days",tone:"review",detail:"Renewal follow-up should be started before the certificate expires."},
 {label:"Carrier agreement",value:"Missing",tone:"block",detail:"Do not activate the carrier until the agreement is received."}
];

export default function CompliancePage(){
 const[running,setRunning]=useState(false),[reviewed,setReviewed]=useState(false),[notice,setNotice]=useState("");
 async function runReview(){if(running)return;setRunning(true);setNotice("");await new Promise(r=>setTimeout(r,1500));setReviewed(true);setRunning(false)}
 function reset(){setReviewed(false);setNotice("")}
 function copyDecision(){navigator.clipboard?.writeText("REVIEW — Do not activate. Cargo coverage is below the broker threshold, COI renewal is due in 18 days, and the carrier agreement is missing.");setNotice("Review decision copied");setTimeout(()=>setNotice(""),2200)}
 return <main><header className="topbar"><div className="topbarInner"><div className="brand"><a href="/" className="brandMark">S</a><span className="brandName">SwiftLabor</span><span className="brandDivider"/><span className="productName">OPERATIONS INTELLIGENCE</span></div><div className="topRight"><span className="liveDot"/> Agent 02 <button className="iconButton"><CircleHelp size={16}/></button></div></div></header>
 <div className="appShell"><aside className="sidebar"><div className="sideLabel">WORKSPACE</div><nav><a href="/" className="sideLink"><Sparkles size={16}/> Scout <span>Agent 01</span></a><div className="active"><ShieldCheck size={16}/> Carrier review</div><div><FileText size={16}/> Document packet <span>Agent 02</span></div></nav><div className="sideBottom"><ShieldCheck size={15}/><div><b>Human approval</b><small>Agent recommends. Your team makes the final activation decision.</small></div></div></aside>
 <section className="workspace"><div className="pageIntro"><div><div className="kicker">SWIFTLABOR / AGENT 02</div><h1>Carrier Compliance Review</h1><p>Turn a new carrier packet into a clear, evidence-backed activation decision.</p></div><div className="agentBadge"><span><ShieldCheck size={14}/></span><div><b>Agent 02</b><small>Document review & exception detection</small></div></div></div>
 <div className="researchCard"><div className="researchTop"><div><span className="stepPill">01</span><div><h2>New carrier packet</h2><p>Demo packet uses public form templates and sanitized sample values. No taxpayer or private carrier credentials are used.</p></div></div><span className="secure"><FileCheck2 size={13}/> Evidence-first review</span></div><div className="packetGrid">{packet.map(doc=><div className={`doc ${doc.status.toLowerCase()}`} key={doc.name}><div className="docIcon"><FileText size={17}/></div><div className="docMain"><b>{doc.name}</b><span>{doc.type}</span><small>{doc.detail}</small></div><span className="docStatus">{doc.status}</span></div>)}</div><div className="reviewActions"><button className="runButton" onClick={runReview} disabled={running}>{running?<><Loader2 size={15} className="spin"/> Reviewing packet…</>:<><ShieldCheck size={15}/> Run compliance review <ArrowUpRight size={15}/></>}</button><span><Check size={12}/> Cross-document checks · public-source verification · exceptions</span></div></div>
 <div className="resultsHeader"><div><div className="kicker">02 / REVIEW DECISION</div><h2>From documents to an operational decision</h2></div>{notice&&<div className="notice">{notice}</div>}</div>
 {!reviewed?<div className="emptyState"><div className="emptyIcon"><FileCheck2 size={20}/></div><b>Packet ready for review</b><p>The agent will compare the packet against broker requirements, surface exceptions and prepare a recommended activation decision.</p><span className="emptyMeta"><Sparkles size={12}/> No final approval is made automatically</span></div>:<ReviewResult onCopy={copyDecision} onReset={reset}/>}</section></div><footer><span>SwiftLabor</span><span>Operations Intelligence · Demo environment · {new Date().getFullYear()}</span></footer></main>
}
function ReviewResult({onCopy,onReset}:{onCopy:()=>void;onReset:()=>void}){return <div className="resultArea"><div className="decisionHero card"><div><div className="decisionEyebrow"><span className="priority warm">REVIEW</span><span>DEMO DECISION</span></div><h3>Do not activate yet</h3><p>Two blocking exceptions and one renewal risk were detected. The agent recommends resolving the packet before the carrier is dispatch-ready.</p></div><div className="decisionScore"><span>READINESS</span><b>62</b><small>/100</small></div></div><div className="checkGrid">{checks.map(c=><div className="checkCard card" key={c.label}><div className={`checkIcon ${c.tone}`}>{c.tone==="pass"?<Check size={15}/>:c.tone==="review"?<AlertTriangle size={15}/>:<XCircle size={15}/>}</div><div><span>{c.label}</span><b>{c.value}</b><p>{c.detail}</p></div></div>)}</div><div className="lowerGrid"><div className="evidenceCard card"><div className="cardHead"><div><span className="kicker">EXCEPTIONS</span><h3>What needs action</h3></div><span className="verified"><AlertTriangle size={12}/> 3 actions</span></div><Exception tone="high" title="Cargo coverage is below threshold" text="Observed demo coverage: $50K. Broker requirement: $100K. Request an updated certificate or endorsement before activation."/><Exception tone="high" title="Carrier agreement is missing" text="Packet is incomplete. Request the signed agreement from the carrier contact."/><Exception tone="medium" title="COI expires in 18 days" text="Create a renewal follow-up now rather than waiting for the expiration date."/></div><div className="sourceCard card"><div className="cardHead"><div><span className="kicker">PUBLIC VERIFICATION</span><h3>Evidence & source trail</h3></div><span className="verified"><Check size={12}/> Traceable</span></div><Source href="https://safer.fmcsa.dot.gov/CompanySnapshot.aspx" title="FMCSA SAFER Company Snapshot" detail="Public carrier identity and safety record lookup" icon={<ShieldCheck size={14}/>}/><Source href="https://www.irs.gov/pub/irs-pdf/fw9.pdf" title="IRS Form W-9" detail="Public current form template · March 2024 revision" icon={<FileText size={14}/>}/><Source href="https://www.govinfo.gov/content/pkg/GOVPUB-A13-PURL-gpo124166/pdf/GOVPUB-A13-PURL-gpo124166.pdf" title="ACORD 25 sample" detail="Public government procurement sample · sanitized reference" icon={<FileText size={14}/>}/><div className="agentFoot"><Sparkles size={13}/><span>Agent 02 · document review + exception engine</span></div></div></div><div className="finalAction card"><div><span className="kicker">RECOMMENDED NEXT STEP</span><h3>Request updated cargo coverage + signed carrier agreement</h3><p>Human review remains required before the carrier is activated for dispatch.</p></div><div className="finalButtons"><button onClick={onCopy}><FileCheck2 size={14}/> Copy decision</button><button className="secondary" onClick={onReset}><RefreshCw size={14}/> Review again</button></div></div></div>}
function Exception({tone,title,text}:{tone:string;title:string;text:string}){return <div className="exception"><span className={`strength ${tone}`}>{tone==="high"?"BLOCK":"REVIEW"}</span><div><b>{title}</b><p>{text}</p></div></div>}
function Source({href,title,detail,icon}:{href:string;title:string;detail:string;icon:ReactNode}){return <div className="sourceRow"><div className="sourceIcon">{icon}</div><div><b>{title}</b><small>{detail}</small></div><a href={href} target="_blank" rel="noreferrer"><ExternalLink size={12}/></a></div>}
